export const adminStats = {
  totalUsers: 45678,
  newUsersThisMonth: 1234,
  totalEvents: 3456,
  newEventsThisMonth: 89,
  platformRevenue: 2345678,
  revenueThisMonth: 234567,
  nftsMinted: 89012,
  nftsThisMonth: 4567,
}

export const allUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    role: "participant",
    status: "active",
    eventsAttended: 12,
    joinedDate: "Jan 15, 2024",
  },
  {
    id: "2",
    name: "Sarah Smith",
    email: "sarah@example.com",
    role: "organizer",
    status: "active",
    eventsAttended: 45,
    joinedDate: "Dec 3, 2023",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    role: "participant",
    status: "active",
    eventsAttended: 8,
    joinedDate: "Feb 20, 2024",
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily@example.com",
    role: "organizer",
    status: "suspended",
    eventsAttended: 23,
    joinedDate: "Nov 10, 2023",
  },
]

export const allEvents = [
  {
    id: "1",
    title: "Tech Innovation Summit 2024",
    organizer: "TechForward Inc",
    category: "Tech",
    date: "March 20, 2024",
    image: "/tech-conference.png",
    status: "approved",
    attendees: 847,
    capacity: 1000,
  },
  {
    id: "2",
    title: "Summer Music Festival",
    organizer: "Live Nation",
    category: "Music",
    date: "June 15, 2024",
    image: "/vibrant-music-festival.png",
    status: "approved",
    attendees: 4523,
    capacity: 5000,
  },
  {
    id: "3",
    title: "Startup Networking Event",
    organizer: "Startup Hub",
    category: "Business",
    date: "April 5, 2024",
    image: "/placeholder.svg",
    status: "pending",
    attendees: 0,
    capacity: 200,
  },
  {
    id: "4",
    title: "Art Gallery Opening",
    organizer: "Art Collective",
    category: "Art",
    date: "May 12, 2024",
    image: "/placeholder.svg",
    status: "rejected",
    attendees: 0,
    capacity: 150,
  },
]

export const platformActivity = [
  {
    id: "1",
    type: "success",
    title: "New Event Approved",
    description: "Tech Innovation Summit 2024 has been approved and published",
    timestamp: "2 hours ago",
  },
  {
    id: "2",
    type: "warning",
    title: "High Ticket Demand",
    description: "Summer Music Festival is 90% sold out - consider increasing capacity",
    timestamp: "5 hours ago",
  },
  {
    id: "3",
    type: "success",
    title: "Payment Processed",
    description: "Platform fee of $12,450 received from event organizers",
    timestamp: "1 day ago",
  },
  {
    id: "4",
    type: "error",
    title: "User Report",
    description: "User reported suspicious activity on event listing #4567",
    timestamp: "1 day ago",
  },
  {
    id: "5",
    type: "success",
    title: "NFT Batch Minted",
    description: "Successfully minted 250 NFT tickets for upcoming events",
    timestamp: "2 days ago",
  },
]
