export const organizerStats = {
  totalEvents: 24,
  eventsThisMonth: 3,
  totalAttendees: 12450,
  attendeesThisMonth: 1250,
  totalRevenue: 487500,
  revenueThisMonth: 45000,
  avgTicketPrice: 89,
}

export const organizerEvents = [
  {
    id: "org-1",
    title: "Tech Innovation Summit 2024",
    description: "Annual technology conference",
    category: "Tech",
    date: "March 20, 2024",
    time: "9:00 AM",
    location: "San Francisco, CA",
    venue: "Moscone Center",
    image: "/tech-conference.png",
    price: 299,
    capacity: 1000,
    attendees: 847,
    status: "upcoming",
  },
  {
    id: "org-2",
    title: "Summer Music Festival",
    description: "Three-day music extravaganza",
    category: "Music",
    date: "June 15-17, 2024",
    time: "12:00 PM",
    location: "Los Angeles, CA",
    venue: "LA Convention Center",
    image: "/vibrant-music-festival.png",
    price: 150,
    capacity: 5000,
    attendees: 4523,
    status: "upcoming",
  },
  {
    id: "org-3",
    title: "Blockchain Developer Workshop",
    description: "Hands-on blockchain development",
    category: "Tech",
    date: "December 10, 2023",
    time: "10:00 AM",
    location: "Miami, FL",
    venue: "Miami Beach Convention Center",
    image: "/blockchain-conference.png",
    price: 199,
    capacity: 300,
    attendees: 285,
    status: "past",
  },
  {
    id: "org-4",
    title: "Art & Design Expo (Draft)",
    description: "Contemporary art showcase",
    category: "Art",
    date: "",
    time: "",
    location: "",
    venue: "",
    image: "",
    price: 0,
    capacity: 0,
    attendees: 0,
    status: "draft",
    lastEdited: "2 days ago",
  },
]
